sed -i 's/\\A/\\mat\{A\}/g' |
sed -i 's/\\B/\\mat\{B\}/g' |
sed -i 's/\\C/\\mat\{C\}/g' |
sed -i 's/\\D/\\mat\{D\}/g' |
sed -i 's/\\E/\\mat\{E\}/g' |
sed -i 's/\\F/\\mat\{F\}/g' |
sed -i 's/\\G/\\mat\{G\}/g' |
sed -i 's/\\H/\\mat\{H\}/g' |
sed -i 's/\\I/\\mat\{I\}/g' |
sed -i 's/\\J/\\mat\{J\}/g' |
sed -i 's/\\K/\\mat\{K\}/g' |
sed -i 's/\\L/\\mat\{L\}/g' |
sed -i 's/\\M/\\mat\{M\}/g' |
sed -i 's/\\N/\\mat\{N\}/g' |
sed -i 's/\\One/\\mathbf\{1\}/g' |
sed -i 's/\\P/\\mat\{P\}/g' |
sed -i 's/\\Q/\\mat\{Q\}/g' |
sed -i 's/\\R/\\mat\{R\}/g' |
sed -i 's/\\S/\\mat\{S\}/g' |
sed -i 's/\\T/\\mat\{T\}/g' |
sed -i 's/\\U/\\mat\{U\}/g' |
sed -i 's/\\V/\\mat\{V\}/g' |
sed -i 's/\\W/\\mat\{W\}/g' |
sed -i 's/\\X/\\mat\{X\}/g' |
sed -i 's/\\Y/\\mat\{Y\}/g' |
sed -i 's/\\argmax/\\mathop\{\\text\{argmax\}\}/g' |
sed -i 's/\\argmin/\\mathop\{\\text\{argmin\}\}/g' |
sed -i 's/\\a/\\vec\{a\}/g' |
sed -i 's/\\b/\\vec\{b\}/g' |
sed -i 's/\\c/\\vec\{c\}/g' |
sed -i 's/\\d/\\vec\{d\}/g' |
sed -i 's/\\e/\\vec\{e\}/g' |
sed -i 's/\\f/\\vec\{f\}/g' |
sed -i 's/\\g/\\vec\{g\}/g' |
sed -i 's/\\h/\\vec\{h\}/g' |
sed -i 's/\\i/\\vec\{i\}/g' |
sed -i 's/\\j/\\vec\{j\}/g' |
sed -i 's/\\k/\\vec\{k\}/g' |
sed -i 's/\\l/\\vec\{l\}/g' |
sed -i 's/\\m/\\vec\{m\}/g' |
sed -i 's/\\n/\\vec\{n\}/g' |
sed -i 's/\\p/\\vec\{p\}/g' |
sed -i 's/\\q/\\vec\{q\}/g' |
sed -i 's/\\r/\\vec\{r\}/g' |
sed -i 's/\\transpose/\{\\mathsf T\}/g' |
sed -i 's/\\s/\\vec\{s\}/g' |
sed -i 's/\\t/\\vec\{t\}/g' |
sed -i 's/\\u/\\vec\{u\}/g' |
sed -i 's/\\vec/\\mathbf/g' |
sed -i 's/\\x/\\vec\{x\}/g' |
sed -i 's/\\y/\\vec\{y\}/g' |
sed -i 's/\\z/\\vec\{z\}/g' |
sed -i 's/\\0/\\vec\{0\}/g' |
sed -i 's/\\v/\\vec\{v\}/g' |
sed -i 's/\\hat/\\widehat/g' |